

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8001
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
